### ISSUE TITLE
Broken download links in the README

### ISSUE THREAD

**Issue by arielpontes** [JeSTeRFLA/FontAwesome-6FREE-6PRO#3]
The links to download the zipped files are broken. I had to browse old versions to be able to download them. For those looking for a  quick download link, you can download the PRO version [here](https://github.com/JeSTeRFLA/FontAwesome-6FREE-6PRO/blob/d4bec5c6e4b9faca1b64502babbd3948ec91a3ad/FontAwesome-6-PRO.7z?raw=true).

**Comment by JeSTeRFLA** [comment]
thank you for pointing that out, i will update the links.

**Comment by JeSTeRFLA** [comment]
https://github.com/JeSTeRFLA/FontAwesome-6FREE-6PRO/releases/tag/FontAwesome6.3
